apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{.Values.mysql.service.type}}
  ports:
    - port: {{.Values.mysql.service.port}}
      targetPort: 3306
  selector:
    app: mysql
