apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: {{.Values.mysql.replicaCount}}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{.Values.mysql.image}}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{.Values.mysql.env.MYSQL_ROOT_PASSWORD}}
            - name: MYSQL_DATABASE
              value: {{.Values.mysql.env.MYSQL_DATABASE}}
            - name: MYSQL_USER
              value: {{.Values.mysql.env.MYSQL_USER}}
            - name: MYSQL_PASSWORD
              value: {{.Values.mysql.env.MYSQL_PASSWORD}}
          resources:
            requests:
              memory: {{.Values.mysql.resources.requests.memory}}
              cpu: {{.Values.mysql.resources.requests.cpu}}
