apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{.Values.wordpress.replicaCount}}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{.Values.wordpress.image}}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{.Values.wordpress.env.WORDPRESS_DB_HOST}}
            - name: WORDPRESS_DB_USER
              value: {{.Values.wordpress.env.WORDPRESS_DB_USER}}
            - name: WORDPRESS_DB_PASSWORD
              value: {{.Values.wordpress.env.WORDPRESS_DB_PASSWORD}}
            - name: WORDPRESS_DB_NAME
              value: {{.Values.wordpress.env.WORDPRESS_DB_NAME}}
          resources:
            requests:
              memory: {{.Values.wordpress.resources.requests.memory}}
              cpu: {{.Values.wordpress.resources.requests.cpu}}
